[project]
name = "uvu"
version = "1.0.0"
description = "UV Upgrader CLI"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "tomli; python_version < '3.14'",
]

[project.scripts]
uvu = "uvu.main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
